logLevel: debug

macros:
  "default_ctx": 4096
  "default_args": "--ctx-size ${default_ctx}"

models:

  "qwen3.5-27b":
     description: "Qwen 3.5 27b"
     macros:
       "default_ctx": 131072
       "temp": 0.6

     cmd: |
       llama-server --port ${PORT}
       --model models/qwen3.5/Qwen3.5-27B-Q8_0.gguf
       --jinja
       --reasoning-format deepseek
       -ngl 99
       -fa on
       -c ${default_ctx}
       -n 32768
       --no-context-shift
       --cache-type-k bf16
       --cache-type-v bf16
       --kv-unified
       --batch-size 4096
       --ubatch-size 1024
       --temp 0.6
       --top-k 20
       --top-p 0.95
       --min-p 0.0
       --repeat-penalty 1.05

     aliases:
      - qwen3.5

  "minimax-m2.5":
     description: "MiniMax M2.5 UD-Q5-K-XL"
     macros:
       "default_ctx": 65536
       "temp": 0.7

     cmd: |
       llama-server --port ${PORT}
       --model models/minimax/MiniMax-M2.5-UD-Q5_K_XL-00001-of-00005.gguf
       -ngl 99
       --ctx-size ${default_ctx}
       --temp ${temp}
       --parallel 4
       --cache-type-k q5_0
       --cache-type-v q5_0
       --flash-attn 1

     aliases:
       - minimax
       - claude-sonnet-4-5
       - claude-sonnet-4-5-20250929
       - claude-haiku-4-5
       - claude-haiku-4-5-20251001
       - claude-opus-4-5
       - claude-opus-4-5-20251101


  "gpt-oss-20b":
     description: "GPT-OSS"
     macros:
      "default_ctx": 200000
      "temp": 07

     cmd: |
      llama-server --port ${PORT}
      -hf unsloth/gpt-oss-20b-GGUF
      --ctx-size ${default_ctx}
      --temp ${temp}

     aliases:
       - gpt-oss

  "kimu-9b":
     description: "Kimu 9b"
     macros:
      "default_ctx": 16384
      "temp": 07

     cmd: |
      llama-server --port ${PORT}
      -hf itzune/Gemma-Kimu-9b-it-Q8_0-GGUF
      --ctx-size ${default_ctx}
      --temp ${temp}
      --chat-template-file models/kimu/gemma2.jinja

     aliases:
       - kimu
       - kimu9b

  "kimu-2b":
    description: "Kimu 2b"
    macros:
      "default_ctx": 16384
      "temp": 07

    cmd: |
      llama-server --port ${PORT}
      -hf itzune/Gemma-Kimu-2b-it-Q8_0-GGUF
      --ctx-size ${default_ctx}
      --temp ${temp}
      --chat-template-file models/kimu/gemma2.jinja

    aliases:
      - "kimu-2b"
      - "kimu2b"
      - "kimu-mini"

  "qwen3vl-8b":
    description: "Qwen3 VL"
    macros:
      "default_ctx": 8192
      "temp": 0.7

    cmd: |
      llama-server --port ${PORT}
      --model models/Qwen3VL/Qwen3-VL-8B-Instruct-UD-Q4_K_XL.gguf
      --mmproj models/Qwen3VL/mmproj-F16.gguf
      --ctx-size ${default_ctx}
      --temp ${temp}
      --flash-attn on
      --jinja
      --n-gpu-layers 99
      --top-k 20
      --top-p 0.8
      --min-p 0.0
      --presence-penalty 1.5

    aliases:
      - "qwen3-vl"
      - "qwen3vl"

  "latxa-qwen3-vl-4b":
    description: "Latxa Qwen3 VL 4b"
    macros:
      "default_ctx": 150000
      "temp": 0.7

    cmd: |
      llama-server --port ${PORT}
      --model models/latxa-vl/HiTZ-Latxa-Qwen3-VL-4B-Instruct-F16.gguf
      --mmproj models/latxa-vl/mmproj-Qwen3VL-4B-Instruct-F16.gguf
      --ctx-size ${default_ctx}
      --temp ${temp}
      --flash-attn on
      --jinja
      --n-gpu-layers 99
      --top-k 20
      --top-p 0.8
      --min-p 0.0
      --presence-penalty 1.5

    aliases:
      - "latxa-vl-4b"

  "latxa-qwen3-vl-8b":
    description: "Latxa Qwen3 VL 8b"
    macros:
      "default_ctx": 150000
      "temp": 0.7

    cmd: |
      llama-server --port ${PORT}
      --model models/latxa-vl/HiTZ-Latxa-Qwen3-VL-8B-Instruct-F16.gguf
      --mmproj models/latxa-vl/mmproj-Qwen3VL-8B-Instruct-F16.gguf
      --ctx-size ${default_ctx}
      --temp ${temp}
      --flash-attn on
      --jinja
      --n-gpu-layers 99
      --top-k 20
      --top-p 0.8
      --min-p 0.0
      --presence-penalty 1.5

    aliases:
      - "latxa-vl"
      - "latxa-vl-8b"

  "latxa-qwen3-vl-32b":
    description: "Latxa Qwen3 VL 32b"
    macros:
      "default_ctx": 150000
      "temp": 0.7

    cmd: |
      llama-server --port ${PORT}
      --model models/latxa-vl/HiTZ-Latxa-Qwen3-VL-32B-Instruct-F16.gguf
      --mmproj models/latxa-vl/mmproj-Qwen3VL-32B-Instruct-F16.gguf
      --ctx-size ${default_ctx}
      --temp ${temp}
      --flash-attn on
      --jinja
      --n-gpu-layers 99
      --top-k 20
      --top-p 0.8
      --min-p 0.0
      --presence-penalty 1.5

    aliases:
      - "latxa-vl-32b"

  "latxa-8b":
    description: "Latxa 8B"
    macros:
      "default_ctx": 150000
      "temp": 0.6

    cmd: |
      llama-server --port ${PORT}
      --model models/latxa/HiTZ-Latxa-Llama-3.1-8B-Instruct-f16.gguf
      --ctx-size ${default_ctx}
      --n-gpu-layers 99
      --batch-size 2048
      --threads 16
      --cache-type-k f16
      --cache-type-v f16
      --flash-attn on

    aliases:
      - latxa-fast

  "latxa-70b":
    description: "Latxa 70B"
    macros:
      "default_ctx": 8192
      "temp": 0.7

    cmd: |
      llama-server --port ${PORT}
      --model models/latxa/Latxa-Llama-3.1-70B-Instruct.gguf
      --ctx-size ${default_ctx}
      --batch-size 2048
      --ubatch-size 512
      --temp ${temp}
      --n-gpu-layers 999
      --threads 24
      --flash-attn on

    aliases:
      - latxa


  "snowflake-arctic-embed-l-v2.0":
    description: "Snowflake Arctic embedding model"
    ttl: 60

    cmd: |
      llama-server --port ${PORT}
      -m models/Snowflake/snowflake-arctic-embed-l-v2.0-q8_0.gguf
      --ctx-size 8192
      --batch-size 8192
      --ubatch-size 4096
      --rope-scaling yarn
      --rope-freq-scale 0.75
      -ngl 99
      --embeddings

    aliases:
      - snowflake

groups:
 "group1":
   concurrencyLimit: 0
   swap: false
   persistent: true
   exclusive: false
   members:
     - "latxa-8b"
     - "kimu-9b"
     - "qwen3vl-8b"

hooks:
  on_startup:
    preload:
      - "latxa-8b"
      - "kimu-9b"
      - "qwen3vl-8b"
